### ISSUE TITLE
Adding Devices

### ISSUE THREAD

**Issue by thehands1** [open-dash/open-dash-diy#1]
I am getting an error when I click on Get Devices from Smartthings. 
TypeError: devices.devices.sort is not a function
    at app.get (C:\open-dash-diy-master\app\controllers\dashboards.js:35:45)
    at Layer.handle [as handle_request] (C:\open-dash-diy-master\node_modules\express\lib\router\layer.js:95:5)
    at next (C:\open-dash-diy-master\node_modules\express\lib\router\route.js:131:13)

Oauth2 seems to be OK since it did connect with ST and show me all of my devices when I connected with ST.  I then clicked on the Get Devices from Smartthings button and I see this error in the console.  I also don't see the weather information at the top of the screen as well.

**Comment by pstuart** [comment]
think I have fixed this now.  Let me know if you get past this issue.
