### ISSUE TITLE
Base64 is not a function

### ISSUE THREAD

**Issue by tombrannstrom** [open-dash/open-dash-diy#22]
Geting following error when i try to start the node..

TypeError: base64 is not a function
    at Function.from (native)
    at Function.from (native)
    at /home/tom/open-dash-diy/app/controllers/home.js:12:26
    at Layer.handle [as handle_request] (/home/tom/open-dash-diy/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/tom/open-dash-diy/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/home/tom/open-dash-diy/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/home/tom/open-dash-diy/node_modules/express/lib/router/layer.js:95:5)
    at /home/tom/open-dash-diy/node_modules/express/lib/router/index.js:281:22
    at Function.process_params (/home/tom/open-dash-diy/node_modules/express/lib/router/index.js:335:12)
    at next (/home/tom/open-dash-diy/node_modules/express/lib/router/index.js:275:10)
    at expressInit (/home/tom/open-dash-diy/node_modules/express/lib/middleware/init.js:40:5)
    at Layer.handle [as handle_request] (/home/tom/open-dash-diy/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/home/tom/open-dash-diy/node_modules/express/lib/router/index.js:317:13)
    at /home/tom/open-dash-diy/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/home/tom/open-dash-diy/node_modules/express/lib/router/index.js:335:12)
    at next (/home/tom/open-dash-diy/node_modules/express/lib/router/index.js:275:10)

**Comment by tombrannstrom** [comment]
Found it, had to old version of nodejs
